2023-06-14 00:08:35,493 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:43,500 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:08:43,537 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:51,551 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:08:51,577 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:08:59,588 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:08:59,644 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:07,651 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:09:07,684 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:15,692 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:09:15,713 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:23,724 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:09:23,749 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:31,759 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:09:39,144 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:48,088 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:09:51,209 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:09:59,215 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:09:59,248 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:07,260 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:10:07,291 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:15,301 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:10:15,331 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:23,340 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:10:23,381 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:31,388 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:10:31,421 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:39,428 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:10:39,448 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:47,460 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:10:47,493 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:10:55,502 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:10:55,544 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:03,552 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:11:03,579 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:11,588 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:11:11,623 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:19,633 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:11:19,663 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:27,672 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:11:27,700 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:35,707 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:11:35,739 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:43,749 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:11:43,782 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:51,788 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:11:51,834 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:11:59,849 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:11:59,876 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:07,885 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:12:07,911 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:15,920 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:12:15,951 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:23,959 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:12:23,984 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:31,995 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:12:32,030 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:40,040 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:12:40,075 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:48,084 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:12:48,121 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:12:56,133 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:12:56,171 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:04,180 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:13:04,223 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:12,232 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:13:12,253 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:20,260 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:13:20,296 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:28,307 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:13:28,330 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:36,340 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:13:36,377 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:44,388 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:13:44,419 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:13:52,429 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:13:52,451 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:00,460 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:14:00,480 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:08,488 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:14:08,520 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:16,531 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:14:16,568 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:24,576 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:14:24,603 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:32,613 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:14:32,643 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:40,656 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:14:40,689 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:48,696 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:14:48,724 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:14:56,735 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:14:56,756 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:04,763 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:15:04,788 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:12,796 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:15:12,823 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:20,832 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:15:20,851 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:28,859 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:15:28,891 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:36,904 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:15:36,932 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:44,940 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:15:44,979 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:15:52,988 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:15:53,029 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:01,040 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:16:01,075 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:09,084 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:16:09,106 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:17,116 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:16:17,148 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:25,156 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:16:25,194 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:33,204 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:16:33,228 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:41,239 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:16:41,269 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:49,276 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:16:49,300 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:16:57,308 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:16:57,343 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:05,352 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:17:05,384 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:13,395 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:17:13,434 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:21,443 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:17:21,470 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:29,480 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:17:29,503 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:37,512 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:17:37,551 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:45,560 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:17:45,595 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:17:53,604 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:17:53,638 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:01,648 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:18:01,680 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:09,688 INFO PID 2213 Playing video file 1.mp4
2023-06-14 00:18:09,724 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:17,732 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:18:17,769 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:25,780 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:18:25,819 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:33,830 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:18:33,854 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:41,860 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:18:41,889 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:49,899 INFO PID 2213 Playing video file 2.mp4
2023-06-14 00:18:49,923 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:18:57,932 INFO PID 2213 Playing video file 5.mp4
2023-06-14 00:18:57,977 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:19:05,988 INFO PID 2213 Playing video file 4.mp4
2023-06-14 00:19:06,012 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-14 00:19:14,020 INFO PID 2213 Playing video file 3.mp4
2023-06-14 00:19:14,042 ERROR PID 2213 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2023-06-18 16:21:57,527 INFO PID 1730 Start player
2023-06-18 16:21:57,546 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:21:57,604 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,607 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:21:57,701 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,708 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:21:57,756 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,776 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:21:57,867 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,869 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:21:57,913 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,915 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:57,991 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:57,998 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:58,087 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,089 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:58,182 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,198 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:21:58,271 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,273 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:58,355 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,373 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:58,453 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,460 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:58,509 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,511 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:21:58,581 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,583 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:58,633 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,638 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:21:58,744 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,746 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:58,800 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,801 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:21:58,888 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,891 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:21:58,965 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:58,976 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:59,061 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,063 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:21:59,117 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,119 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:59,190 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,192 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:21:59,240 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,242 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:59,318 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,322 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:59,430 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,432 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:59,572 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,580 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:59,693 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,696 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:21:59,771 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,774 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:21:59,878 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,884 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:21:59,939 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:21:59,942 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:00,004 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,008 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:00,068 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,071 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:00,206 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,214 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:00,310 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,330 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:00,393 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,396 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:00,489 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,498 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:00,548 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,553 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:00,614 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,617 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:00,665 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,667 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:00,740 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,742 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:00,780 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,782 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:00,837 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,840 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:00,896 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,898 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:00,944 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,948 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:00,984 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:00,988 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:01,024 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,026 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:01,063 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,065 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:01,120 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,128 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:01,211 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,214 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:01,311 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,313 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:01,368 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,370 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:01,399 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,401 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:01,435 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,437 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:01,479 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,486 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:01,580 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,596 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:01,727 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,737 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:01,840 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:01,864 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:02,005 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:02,008 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:02,074 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:02,076 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:02,138 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:02,140 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:02,692 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:02,708 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:03,280 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:03,283 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:03,865 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:03,868 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:04,397 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:04,398 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:04,890 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:04,894 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:04,964 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:04,969 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:05,244 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:05,249 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:05,332 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:05,336 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:05,656 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:05,658 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:05,725 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:05,728 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:05,802 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:05,806 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:06,037 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,039 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:06,259 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,261 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:06,298 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,302 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:06,509 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,513 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:06,585 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,595 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:06,735 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,744 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:06,853 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:06,856 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:07,002 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,016 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:07,091 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,095 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:07,292 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,295 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:07,402 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,413 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:07,589 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,595 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:07,684 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,692 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:07,942 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:07,961 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:08,058 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,062 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:08,264 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,266 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:08,322 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,323 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:08,415 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,418 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:08,517 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,519 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:08,566 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,568 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:08,775 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,777 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:08,915 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,917 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:08,972 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:08,985 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:09,090 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:09,097 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:09,346 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:09,361 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:09,454 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:09,458 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:09,691 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:09,694 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:09,773 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:09,777 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:10,101 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,104 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:10,314 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,321 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:10,390 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,391 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:10,466 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,473 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:10,522 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,527 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:10,781 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,785 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:10,933 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:10,941 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:11,228 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,231 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:11,339 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,344 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:11,535 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,538 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:11,591 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,594 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:11,653 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,656 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:11,928 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,932 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:11,988 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:11,992 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:12,059 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:12,067 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:12,281 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:12,291 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:12,588 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:12,596 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:12,668 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:12,670 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:12,843 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:12,860 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:13,100 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,173 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:13,432 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,436 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:13,482 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,485 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:13,696 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,697 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:13,844 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,846 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:13,920 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:13,924 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:14,169 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:14,175 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:14,490 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:14,508 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:14,746 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:14,748 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:14,923 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:14,927 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:15,037 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,042 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:15,162 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,168 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:15,334 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,351 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:15,559 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,562 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:15,637 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,639 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:15,820 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,824 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:15,974 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:15,980 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:16,215 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,224 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:16,321 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,323 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:16,514 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,516 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:16,590 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,600 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:16,727 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,735 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:16,917 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:16,920 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:17,015 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,022 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:17,173 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,176 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:17,254 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,262 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:17,430 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,463 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:17,634 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,647 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:17,896 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:17,915 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:18,082 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:18,085 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:18,198 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:18,201 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:18,390 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:18,392 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:18,711 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:18,713 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:18,776 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:18,780 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:19,024 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,031 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:19,189 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,193 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:19,245 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,247 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:19,403 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,406 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:19,605 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,630 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:19,886 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:19,890 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:22:20,153 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,156 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:20,231 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,237 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:20,340 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,343 INFO PID 1730 Playing video file 5.mp4
2023-06-18 16:22:20,382 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,384 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:20,634 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,637 INFO PID 1730 Playing video file 2.mp4
2023-06-18 16:22:20,733 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,735 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:20,897 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:20,902 INFO PID 1730 Playing video file 3.mp4
2023-06-18 16:22:21,084 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:21,086 INFO PID 1730 Playing video file 4.mp4
2023-06-18 16:22:21,181 ERROR PID 1730 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 50, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:22:21,185 INFO PID 1730 Playing video file 1.mp4
2023-06-18 16:23:58,200 INFO PID 2885 Start player
2023-06-18 16:24:17,925 INFO PID 2885 Playing video file 3.mp4
2023-06-18 16:24:18,198 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:21,323 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:24:21,764 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:34,967 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:24:35,343 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:39,637 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:24:39,782 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:42,198 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:24:42,461 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:44,092 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:24:44,490 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:46,062 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:24:46,252 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:48,085 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:24:48,311 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:24:49,497 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:24:49,694 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:07,632 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:25:07,874 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:09,010 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:25:09,235 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:10,780 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:25:11,044 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:15,953 INFO PID 2885 Playing video file 3.mp4
2023-06-18 16:25:16,368 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:18,913 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:25:19,276 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:23,894 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:25:24,134 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:27,107 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:25:27,382 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:28,380 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:25:28,641 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:29,655 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:25:29,788 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:32,073 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:25:32,333 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:33,432 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:25:33,674 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:34,711 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:25:35,066 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:36,349 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:25:36,632 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:25:37,644 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:25:37,966 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:13,772 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:27:14,056 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:14,680 INFO PID 2885 Playing video file 3.mp4
2023-06-18 16:27:15,099 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:15,359 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:15,496 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:15,707 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:27:16,039 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:16,162 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:27:16,430 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:16,559 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:27:16,799 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:16,823 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:27:17,128 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:17,131 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:27:17,479 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:20,822 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:21,119 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:21,948 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:27:22,199 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:22,202 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:22,326 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:22,349 INFO PID 2885 Playing video file 3.mp4
2023-06-18 16:27:22,508 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:22,633 INFO PID 2885 Playing video file 2.mp4
2023-06-18 16:27:22,980 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:23,048 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:27:23,153 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:23,512 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:23,690 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:23,762 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:27:24,107 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:24,117 INFO PID 2885 Playing video file 4.mp4
2023-06-18 16:27:24,449 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:24,545 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:24,794 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:24,800 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:24,963 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:24,978 INFO PID 2885 Playing video file 1.mp4
2023-06-18 16:27:25,128 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:27:25,205 INFO PID 2885 Playing video file 5.mp4
2023-06-18 16:27:25,509 ERROR PID 2885 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:31:04,033 INFO PID 4682 Start player
2023-06-18 16:31:36,737 INFO PID 4682 Playing video file 2.mp4
2023-06-18 16:31:37,033 ERROR PID 4682 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:31:48,116 INFO PID 4682 Playing video file 2.mp4
2023-06-18 16:31:48,488 ERROR PID 4682 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 56, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 16:32:30,186 INFO PID 5004 Start player
2023-06-18 16:33:32,000 INFO PID 5261 Start player
2023-06-18 16:33:32,037 INFO PID 5261 Playing video file 2.mp4
2023-06-18 16:33:47,156 INFO PID 5261 Playing video file 3.mp4
2023-06-18 16:34:02,332 INFO PID 5261 Playing video file 5.mp4
2023-06-18 16:35:53,892 INFO PID 5560 Start player
2023-06-18 16:35:53,905 INFO PID 5560 Playing video file 4.mp4
2023-06-18 16:42:49,619 INFO PID 5938 Start player
2023-06-18 16:42:49,643 INFO PID 5938 Playing video file 3.mp4
2023-06-18 16:43:04,720 INFO PID 5938 Playing video file 3.mp4
2023-06-18 16:43:19,937 INFO PID 5938 Playing video file 3.mp4
2023-06-18 16:44:31,579 INFO PID 6188 Start player
2023-06-18 16:44:31,604 INFO PID 6188 Playing video file 4.mp4
2023-06-18 16:44:46,693 INFO PID 6188 Playing video file 2.mp4
2023-06-18 16:45:01,841 INFO PID 6188 Playing video file 5.mp4
2023-06-18 16:48:53,441 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:49:08,620 INFO PID 6518 Playing video file 2.mp4
2023-06-18 16:49:23,672 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:49:38,728 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:49:53,764 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:50:08,801 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:50:23,909 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:50:39,064 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:50:54,177 INFO PID 6518 Playing video file 2.mp4
2023-06-18 16:51:09,309 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:51:24,448 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:51:39,599 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:51:54,724 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:52:09,928 INFO PID 6518 Playing video file 2.mp4
2023-06-18 16:52:25,113 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:52:40,184 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:52:55,250 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:53:10,365 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:53:25,453 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:53:40,626 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:53:55,675 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:54:10,732 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:54:25,771 INFO PID 6518 Playing video file 2.mp4
2023-06-18 16:54:40,811 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:54:55,847 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:55:10,883 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:55:25,924 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:55:40,966 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:55:56,004 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:56:11,044 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:56:26,089 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:56:41,147 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:56:56,181 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:57:11,227 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:57:26,268 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:57:41,316 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:57:56,385 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:58:11,423 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:58:26,467 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:58:41,507 INFO PID 6518 Playing video file 5.mp4
2023-06-18 16:58:56,546 INFO PID 6518 Playing video file 1.mp4
2023-06-18 16:59:11,592 INFO PID 6518 Playing video file 3.mp4
2023-06-18 16:59:26,650 INFO PID 6518 Playing video file 4.mp4
2023-06-18 16:59:41,695 INFO PID 6518 Playing video file 1.mp4
2023-06-18 17:00:17,855 INFO PID 7049 Start player
2023-06-18 17:00:55,923 INFO PID 7049 Playing video file 2.mp4
2023-06-18 17:00:56,085 ERROR PID 7049 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 57, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 17:01:15,612 INFO PID 7049 Playing video file 1.mp4
2023-06-18 17:01:15,920 ERROR PID 7049 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 57, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 17:01:22,098 INFO PID 7049 Playing video file 3.mp4
2023-06-18 17:01:22,310 ERROR PID 7049 Exception occurred
Traceback (most recent call last):
  File "/home/ichiro/factory-mockup/mockup.py", line 57, in send_data
    sock.connect((MODBUS_IP, MODBUS_PORT))
ConnectionRefusedError: [Errno 111] Connection refused
2023-06-18 17:01:33,402 INFO PID 7049 Playing video file 4.mp4
